monitor.alsa.rules = [
  {
    matches = [
      {
        "node.name" = "~alsa_output.*"
        "node.description" = "~.*Earphone speaker.*"
      }
    ]
    actions = {
      update-props = {
        "node.description" = "CortadoDeck Headset/Builtin Speaker"
        "node.nick"        = "Speaker"
        "session.default-volume" = 0.60
      }
    }
  },
  {
    matches = [
      {
        "node.name" = "~alsa_input.*"
        "node.description" = "~.*Builtin microphone.*"
      }
    ]
    actions = {
      update-props = {
        "node.description" = "CortadoDeck Headset/Builtin Mic"
        "session.default-volume" = 0.80
      }
    }
  },
  {
    matches = [
      {
        "node.name" = "~alsa_output.*"
        "node.description" = "~.*I2S output.*"
      }
    ]
    actions = {
      update-props = {
        "node.disabled" = true
      }
    }
  },
  {
    matches = [
      {
        "node.name" = "~alsa_input.*"
        "node.description" = "~.*Digital microphone.*"
      }
    ]
    actions = {
      update-props = {
        "node.disabled" = true
      }
    }
  }
]
